apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  REFRESH_TOKEN_SECRET: {{ .Values.secrets.refreshTokenSecret | quote }}
  REFRESH_TOKEN_EXPIRY: {{ .Values.secrets.refreshTokenExpiry | quote }}
  PORT: {{ index .Values.services "auth-service" "port" | quote }}