{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $name }}
    {{- include "healthcare.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
  type: ClusterIP
---
{{- end }}