
# helm/values.yaml
global:
  registry: "942617679324.dkr.ecr.us-east-1.amazonaws.com"
  imageTag: "1ef0ddc90929"
  namespace: healthcare


services:
  frontend:
    port: 3000
    replicas: 1
    image: eks-healthcare-frontend
    healthPath: "/health"

  auth-service:
    port: 8001
    replicas: 1
    image: eks-healthcare-auth-service
    healthPath: "/health"

  doctor-service:
    port: 8002
    replicas: 1
    image: eks-healthcare-doctor-service
    healthPath: "/health"

  patient-service:
    port: 8003
    replicas: 1
    image: eks-healthcare-patient-service
    healthPath: "/health"

  appointment-service:
    port: 8004
    replicas: 1
    image: eks-healthcare-appointment-service
    healthPath: "/health"